version: "3.8"
services:
  invoicify_db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  invoicify_app_h2:
#  invoicify_app_postgres:
    image: invoicify:dev
    ports:
      - "2000:8080"
#      - "1000:8080"
    environment:
#     SPRING_PROFILES_ACTIVE: h2
      SPRING_PROFILES_ACTIVE: postgres
    depends_on:
      - invoicify_db

